service: tic-tac-toe-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:

  # Defines an HTTP API endpoint that calls the main function in api/create.js
  # - path: url path is /games
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: api/create.main
    events:
      - http:
          path: games
          method: post
          cors: true
          authorizer: aws_iam

  # Defines an HTTP API endpoint that calls the main function in get.js
  # - path: url path is /games/{id}
  # - method: GET request
  get:
    handler: api/get.main
    events:
      - http:
          path: games/{id}
          method: get
          cors: true
          authorizer: aws_iam

  # Defines an HTTP API endpoint that calls the main function in list.js
  # - path: url path is /games
  # - method: GET request
  list:
    handler: api/list.main
    events:
      - http:
          path: games
          method: get
          cors: true
          authorizer: aws_iam

  # Defines an HTTP API endpoint that calls the main function in update.js
  # - path: url path is /games/{id}
  # - method: PUT request
  update:
    handler: api/update.main
    events:
      - http:
          path: games/{id}
          method: put
          cors: true
          authorizer: aws_iam

  # Defines an HTTP API endpoint that calls the main function in delete.js
  # - path: url path is /games/{id}
  # - method: DELETE request
  delete:
    handler: api/delete.main
    events:
      - http:
          path: games/{id}
          method: delete
          cors: true
          authorizer: aws_iam
